### ISSUE TITLE
Haplotype log2Med bins and sliding window size?

### ISSUE THREAD

**Issue by jah000** [kuzobuta/scRepliseq-Pipeline#2]
Hi, thanks for the resource. 

I think I've found a discrepancy between your Nature protocols publication and the R haplotype script files published on github.
 
When describing the haplotype approach (Nature Protocol Box 3) you state "1-Mb bins for smoothing (200-kb sliding windows)." However, in the R script (https://github.com/kuzobuta/scRepliseq-Pipeline/blob/master/scripts/haplotype-resolved-analysis/Step5_Haplotype_log2med.R) the window is 1Mb and sliding id 40Kb. 

Would you be able to clarify this for me?

Many thanks

**Comment by kuzobuta** [comment]
Thanks for the comment. That was typo. I updated sliding kb to 200kb.
